spring:
  cloud:
    openservicebroker:
      api-version: 2.13
      api-version-check-enabled: false
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
          temp:
            use_jdbc_metadata_defaults: false
      show-sql: false
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: user
    password: ~
    hikari:
      maximum-pool-size: 3
logging:
  level:
    com.demo.obs.crossbrowser: debug
  file: broker.log
